"""add_password_hash_to_users

Revision ID: 292e86eacc7f
Revises: 002
Create Date: 2026-01-12 19:00:13.425866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '292e86eacc7f'
down_revision: Union[str, Sequence[str], None] = '002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Delete existing users since we're changing auth system (they used OAuth)
    op.execute("DELETE FROM workout_entries")
    op.execute("DELETE FROM workout_plans")
    op.execute("DELETE FROM exercises")
    op.execute("DELETE FROM users")

    # Add password_hash column
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=False))
    op.alter_column('workout_plans', 'tags',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workout_plans', 'tags',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True)
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
